### PR TITLE
s2cg button after loging a cache

### LINKED ISSUE #85: s2cg button after loging a cache
grafik
Sometimes after loging a cache, the script shows a s2cg button on the top of the page.
Should that be so?

### PR DESCRIPTION
**Pull request by capoaira**
The button is shown because waitForKeyElements() find new Elements after logging and a Cache
fix #85

### CODE REVIEW

**Comment by bekuno** [comment]
Interesting catch.
Are you sure that this is not needed on other pages?

**Comment by capoaira** [comment]
Yes, this function is called only once with 
```javascript
    window.waitForKeyElements(".cache-details", addSend2cgeoColumn, false);
```
`addSend2cgeoColumn` is only for the new search

**Comment by bekuno** [comment]
I mean - before the change it was called outside the 
~~~
if (location) {}
~~~
tree, but now only inside geocaching.com new search.
~~~
 } else if(document.getElementById('searchResultsTable') !== null) {
~~~

**Comment by capoaira** [comment]
Yes, it's only use for the new search. Otherwise the second argument has an other function. (See line 175 and the comment before)
For other pages the the function must be called again.

**Pull request merged**
