### PR TITLE
s2cg button on searchmap popup

### LINKED ISSUE #129: Add "Send2cgeo" to right click menu of caches at the live map
grafik

A "Send2cgeo" button would be pretty awesome in that right click menu ;-)

### PR DESCRIPTION
**Pull request by capoaira**
fix #129

### CODE REVIEW

**Review by fm-sys — APPROVED** [review]
LGTM and tests in my browser were all fine! Let's merge...

**Comment by fm-sys** [comment]
@Lineflyer looks like I have no permission to merge PR's in this repo. Would you merge this PR or give me the permission to do so? ;-)

**Comment by Lineflyer** [comment]
@fm-sys Strange. I suspect it was a wrong setting in branch protection rules. Please try again.

**Comment by fm-sys** [comment]
@Lineflyer thanks! Now it was working 👍

**Pull request merged**
