### PR TITLE
Fix Premium check for Geocaching.com

### LINKED ISSUE #36: Version 0.38 stopped working
It gives me this error in chrome console:
`ERROR: Execution of script 'Send to c:geo' failed! Cannot read property 'children' of undefined`

I temporarily fixed it by manually setting the variable premium to false (I deleted the block of code checking the status of membership)

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
closes #36 

thanks to @geronimo0812 for noticing the change

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
Huh, now it's again `li-membership` O_o

**Comment by Lineflyer** [comment]
I did q quick test of this PR and the script was working fine for PM and BM.
@KeyWeeUsr Do you consider it final? From my side we could merge and release this as v 0.39.

**Comment by KeyWeeUsr** [comment]
I think so. I'm not sure what was Wulf's issue with it if it works for you except that he still might have been using an old version. Just to be sure, ping someone with premium to test it on one more account and then feel free to merge :)

**Comment by Lineflyer** [comment]
@KeyWeeUsr Are you able to squash the commits into one or create a new single commit PR? As I am only using the Github UI I cannot do that.

**Comment by SammysHP** [comment]
@Lineflyer 
Of course, you can do it via GitHub. Click on the arrow next to "Merge pull request" and select "Squash and merge".

**Pull request merged**
