### PR TITLE
typing bug

### PR DESCRIPTION
**Pull request by capoaira**

### CODE REVIEW

**Comment by Lineflyer** [comment]
@capoaira Is this also a functional bug, meaning we should release it asap or only cosmetic?

**Comment by capoaira** [comment]
It is also a functional bug: https://forums.geocaching.com/GC/index.php?/topic/343005-gc-little-helper-ii/page/5/&tab=comments#comment-5875893

**Comment by Lineflyer** [comment]
Thanks @capoaira 
The change is pretty straight forward. I will put it through to `release` in a minute, and would kindly ask you to doublecheck after updating.

**Comment by Lineflyer** [comment]
script version 2021.02.24 has been released!

**Pull request merged**
